const { jsPDF } = require("../../Admin.Web/node_modules/jspdf/dist/jspdf.node.min.js");
const fs = require("fs");
const path = require("path");

const sections = [
["1. System Overview", ["The Jiggling Pig payment system combines a customer touchscreen kiosk, a Square Terminal card reader, and the Jiggling Pig Admin Panel.", "The kiosk lets customers build an order, select sides, review prices, enter a pickup name and optional phone number, and choose a payment method.", "The Square Terminal accepts tap, chip, and swipe payments. The kiosk sends the total to the Terminal and waits for Square to report the result.", "Authorized staff use the Admin Panel to manage kiosk devices, products, inventory, orders, payments, refunds, and the Kitchen Queue."]],
["2. Important Payment Rules", ["Never unplug, refresh, close, or restart either device while a payment is processing.", "The total shown on the kiosk must match the total shown on the Square Terminal.", "A payment is not considered finished until the kiosk displays the confirmation and order number.", "If a result is uncertain, check the order and Square payment records before charging the customer again.", "Never ask for or record a complete card number, security code, or PIN.", "The kiosk does not support cash, checks, split tender, partial payments, or customer-initiated refunds."]],
["3. Daily Opening Check", ["Inspect the kiosk screen, stand, power cable, and network connection. Clean the touchscreen with an approved product.", "Inspect the Square Terminal, charging cable, card slot, battery level, and network indicator. Confirm it is not stuck on a sign-in or setup screen.", "The kiosk should show 'Hungry? Order Here.' and 'Tap to Start.' If it shows 'Kiosk Setup,' activation is required.", "Before opening, create a small test order, send it to the Terminal, verify the totals match, complete the approved test method, and confirm the order reaches the Admin Panel and Kitchen Queue."]],
["4. Starting an Order", ["Tap 'Tap to Start' on the attract screen.", "Choose a category such as Jiggling Food Menu, Sides, or Jiggling Pig Products. Food may be grouped under Combo Items, Sides, Other Items, and Drinks.", "Only products that are in stock and enabled for kiosk sales should appear.", "Use 'Start Over' only when the entire current order should be discarded. It clears the cart, side choices, customer details, and active order information."]],
["5. Adding and Editing Cart Items", ["Tap a product once to add one unit. Tap it again to increase the quantity of the same selection.", "Under 'Your Order,' use + to increase quantity and - to decrease it. Decreasing to zero removes the line.", "Use 'Remove' to delete an unwanted product. Confirm the subtotal changes after every correction.", "If a combo has the wrong sides, remove the combo and add it again with the correct selections.", "Before checkout, verify every product, quantity, side, duplicate-side charge, and subtotal."]],
["6. Combo Meals and Side Selection", ["A combo opens a window labeled 'Choose [number] sides for [product].' The counter shows how many required sides have been chosen.", "Select the required number of sides and press 'Add to Order.' Use 'Clear' to restart the choices or 'Cancel' to leave without adding the combo.", "Selecting some sides more than once may display 'Extra [side]?' with 'No, Go Back' and 'Yes, Add It (+$X).' Explain and confirm the upcharge before accepting it."]],
["7. Customer Information", ["Press 'Checkout' after the cart is correct.", "On 'Who's this order for?', enter the required pickup name. Review the spelling because staff will use it when calling the order.", "The phone number is optional. Enter it only with the customer's permission and verify every digit.", "Do not promise an order-ready text until management has confirmed that texting is active and tested.", "Use 'Back' to correct the cart. Use 'Continue to Payment' when all information is correct."]],
["8. Choosing a Payment Method", ["The Payment screen shows the customer name, total, and available methods.", "'Pay on the card reader' instructs the customer to tap, insert, or swipe on the reader. If it says 'Card reader not connected yet,' do not use it.", "'Enter card on screen' loads a secure Square form. If it says 'Not available,' the required Square configuration is incomplete.", "Use 'Back' if the order or customer information needs correction."]],
["9. Paying on the Square Terminal", ["Confirm the kiosk total with the customer, then select 'Pay on the card reader' once.", "Wait for 'Follow the card reader.' Confirm the Square Terminal wakes and displays the identical amount.", "For contactless payment, hold the card, phone, or watch near the contactless symbol until the Terminal responds.", "For chip payment, insert the chip end first and leave the card in place until the Terminal says to remove it.", "Swipe only when appropriate and allowed by the Terminal. Follow every prompt shown on the Terminal.", "Wait for both the Terminal and kiosk. The kiosk checks Square every few seconds, so a short delay is normal."]],
["10. On-Screen Card Payment", ["Select 'Enter card on screen' and wait for the secure form. Do not refresh while it says 'Loading secure card form...'.", "The customer should enter their own card number, expiration date, security code, and postal code when requested.", "Review the total and press 'Pay $X' once. Wait while the button says 'Processing...'.", "If the form will not load, press Back, check the internet connection, try once more, or use the Square Terminal.", "This option requires the Square application ID, location ID, access configuration, correct environment, and Square as the active payment gateway."]],
["11. Successful Payment", ["A successful payment displays 'Thanks, [name]!', an order number, and pickup instructions.", "Confirm the order number is visible, the payment is captured or completed, and the order appears in the Kitchen Queue.", "Tell the customer the pickup name or number. Press 'Done,' or allow the confirmation to return to the start screen automatically after about 20 seconds."]],
["12. Canceling a Payment", ["Cancel if the customer changes their mind, the amount is wrong, the wrong method was selected, or the Terminal cannot complete the prompts.", "Press 'Cancel Payment,' stop interacting with the Terminal, and wait for the kiosk to return to payment choices.", "If canceled on the reader, the kiosk should say 'Payment was canceled on the reader. Please try again.'", "Do not begin another attempt until the first one is clearly canceled."]],
["13. Timeout and Decline", ["A Terminal attempt may time out after about three minutes and display 'The card reader timed out. Please try again.' Verify the first attempt did not complete before retrying.", "For a decline, say: 'The payment was not approved. You may try again or use another card.' Do not guess why the bank declined it.", "Try a declined card only once more when appropriate. If declined again, request another card."]],
["14. Reader Connection Failure", ["If the kiosk says 'Could not reach the card reader,' confirm the Terminal has power, internet, the correct pairing, and no other active payment.", "Wait briefly and retry once. If the on-screen card option is available, use it instead.", "If both methods fail, stop kiosk payments and notify a manager."]],
["15. Uncertain Payment: Do Not Double-Charge", ["Treat the payment as uncertain if the Terminal says approved but the kiosk waits, the internet drops, the browser refreshes, or the customer receives a bank notice without kiosk confirmation.", "Record the customer name, amount, time, and any order number. Check the kiosk, Kitchen Queue, Admin Panel order, stored payment status, and Square transaction activity.", "Compare the amount, time, status, and order reference. If completed, fulfill the order and do not charge again. If canceled or failed, retry. If pending, ask a manager to investigate."]],
["16. Payment Status Reference", ["Pending: started but not final; wait and verify.", "Authorized: approved but may still require completion; do not duplicate the charge.", "Captured or Completed: payment succeeded; fulfill the order.", "Canceled: stopped before completion; customer may retry.", "Failed: did not complete; verify, then retry or use another method.", "Refunded: money was returned to the original payment method."]],
["17. Kiosk Activation", ["If 'Kiosk Setup' appears, obtain the approved setup link or token from the Admin Panel. The token normally begins with ksk_.", "Enter the complete token or link, press 'Activate Kiosk,' and wait while it says 'Connecting...'. Confirm the attract screen appears.", "Treat the token like a password: never publish, photograph, or include it in a guide. Revoke the kiosk if the token may have been exposed."]],
["18. Pairing a Square Terminal", ["In the Admin Panel, open kiosk device management, select the correct kiosk, and start Terminal pairing.", "On the Square Terminal, open Settings, sign out if necessary, and enter the generated device code.", "Wait for pairing confirmation, then run a test order to confirm the correct Terminal receives the correct amount.", "Do not open the kiosk for customers until pairing and a test transaction succeed."]],
["19. Refunds", ["Customers cannot refund from the kiosk. An authorized employee must locate the correct order or payment in the Admin Panel.", "Verify the order number, date, customer, original amount, payment status, gateway, reason, and any required approval.", "Submit the refund, wait for the result, and verify the record says Refunded. Refresh and check Square before retrying a refund.", "Tell the customer the refund was submitted to the original method and that their bank determines when it appears."]],
["20. Kitchen Queue Handoff", ["After payment, confirm the order appears in the Kitchen Queue with the correct name, number, products, quantities, and sides.", "If payment succeeded but the order is missing, refresh the queue and search the Admin Panel. Do not charge again; notify a manager.", "Call the pickup name or order number and use the configured notification process when the food is ready."]],
["21. Product and Inventory Problems", ["A missing item may be deleted, out of stock, hidden from the kiosk, or assigned to the wrong category.", "Verify stock is above zero, kiosk visibility is enabled, and the category is correct.", "Menu changes can take several minutes to refresh. Avoid changing prices during an active checkout."]],
["22. Square Terminal Troubleshooting", ["Blank screen: check power and charging; remove the device from service if it will not wake.", "Offline: restore the approved network connection before retrying.", "Wrong amount: cancel immediately, correct the cart, and restart payment.", "No payment received: check pairing, network, power, and whether another payment is active.", "Card will not read: try contactless, then chip, then another card. Never force a card into the slot."]],
["23. Kiosk Troubleshooting", ["Unresponsive screen: clean and dry it, check power, and restart only when no payment is active.", "Setup screen: reactivate with an authorized token and run a test order.", "Secure card form missing: check internet, return to payment choices, retry once, then use the Terminal.", "Empty menu: check internet, stock, visibility, and categories. Refresh only when no payment is active.", "For any 'Payment failed' message, verify Square and order records before trying again."]],
["24. Safe Restart Procedure", ["Before restarting, confirm no customer is entering payment and no payment is active or pending.", "Record any uncertain order number, time, and amount.", "Restart the kiosk session first. Restart the Terminal only if necessary. Wait for reconnection, verify activation and pairing, then run a test transaction."]],
["25. End-of-Day Procedure", ["Review all kiosk orders and look for pending, failed, canceled, duplicate, and refunded payments.", "Compare paid kiosk orders with Square completed payments and refund totals. Investigate every unclear status.", "Return the kiosk to the attract screen, clean both devices, connect the Terminal to power, hide admin pages, and report damage."]],
["26. Payment Incident Record", ["Record date/time, kiosk location, customer first name, order number, amount, attempted method, kiosk message, Terminal message, status, Kitchen Queue result, employee, manager, and resolution.", "Never record a complete card number, security code, PIN, or other sensitive card information."]],
["27. Current Limitations", ["No cash, checks, split tender, partial payments, kiosk coupons, or customer-initiated refunds.", "No customer-facing printed, emailed, or texted receipt option is currently exposed in the kiosk.", "A phone number is collected, but ready-text behavior must be separately verified before it is promised.", "Menu and stock updates may take several minutes to appear.", "A real end-to-end Square test payment must be completed before production use is considered fully verified."]],
["28. Quick Payment Checklist", ["Before: verify items, quantities, sides, upcharges, name, total, and Terminal connection.", "During: match the Terminal amount to the kiosk, follow prompts, leave chip cards inserted, and never press Pay repeatedly.", "After: confirm the order number, Kitchen Queue entry, completed payment status, pickup information, and return to the start screen."]]
];

const doc = new jsPDF({ unit: "pt", format: "letter" });
const W = 612, H = 792, left = 54, right = 54, top = 58, bottom = 55;
let y = top;
const blue = [36, 82, 117], teal = [19, 155, 138], dark = [36, 50, 65], gray = [90, 105, 120];
function footer(){ const n=doc.getNumberOfPages(); doc.setDrawColor(215); doc.line(left,H-38,W-right,H-38); doc.setFont("helvetica","normal"); doc.setFontSize(8); doc.setTextColor(...gray); doc.text("Jiggling Pig Operations | Kiosk & Square Terminal User Guide",left,H-23); doc.text(String(n),W-right,H-23,{align:"right"}); }
function newPage(){ footer(); doc.addPage(); y=top; }
function ensure(h){ if(y+h>H-bottom) newPage(); }
function wrapped(text,size=10,width=W-left-right,style="normal",color=dark,indent=0){ doc.setFont("helvetica",style); doc.setFontSize(size); doc.setTextColor(...color); const lines=doc.splitTextToSize(text,width-indent); ensure(lines.length*(size*1.35)+5); doc.text(lines,left+indent,y); y += lines.length*(size*1.35)+7; }
function heading(text){ ensure(42); doc.setFont("helvetica","bold"); doc.setFontSize(15); doc.setTextColor(...blue); doc.text(text,left,y); y+=8; doc.setDrawColor(...teal); doc.setLineWidth(1.5); doc.line(left,y,W-right,y); y+=18; }
function bullet(text){ const lines=doc.splitTextToSize(text,W-left-right-20); ensure(lines.length*13.5+5); doc.setFillColor(...teal); doc.circle(left+4,y-3,2,"F"); doc.setFont("helvetica","normal"); doc.setFontSize(10); doc.setTextColor(...dark); doc.text(lines,left+16,y); y += lines.length*13.5+5; }

// Cover
 doc.setFillColor(...blue); doc.rect(0,0,W,210,"F"); doc.setFillColor(...teal); doc.rect(0,210,W,10,"F"); doc.setTextColor(255,255,255); doc.setFont("helvetica","bold"); doc.setFontSize(30); doc.text("JIGGLING PIG",left,92); doc.setFontSize(23); doc.text("Kiosk & Square Terminal",left,133); doc.text("Payment Processing User Guide",left,164); doc.setTextColor(...dark); doc.setFontSize(15); doc.text("Detailed operating, payment, safety, and troubleshooting instructions",left,277); doc.setFont("helvetica","normal"); doc.setFontSize(11); doc.setTextColor(...gray); doc.text("Prepared for Jiggling Pig Operations",left,315); doc.text("Version: August 2026",left,335);
 doc.setFillColor(244,247,250); doc.roundedRect(left,390,W-left-right,135,8,8,"F"); doc.setFont("helvetica","bold"); doc.setFontSize(12); doc.setTextColor(...blue); doc.text("IMPORTANT",left+20,420); doc.setFont("helvetica","normal"); doc.setFontSize(10); doc.setTextColor(...dark); const coverNote=doc.splitTextToSize("A payment is not complete until the kiosk displays the confirmation and order number. If a payment result is uncertain, check the Admin Panel and Square records before charging the customer again.",W-left-right-40); doc.text(coverNote,left+20,446); footer();

// TOC
 doc.addPage(); y=top; heading("Table of Contents"); doc.setFont("helvetica","normal"); doc.setFontSize(10); sections.forEach((s,i)=>{ ensure(19); doc.setTextColor(...dark); doc.text(s[0],left,y); doc.setTextColor(...gray); doc.text(String(i+3),W-right,y,{align:"right"}); doc.setDrawColor(225); doc.setLineDashPattern([1,2],0); doc.line(left+doc.getTextWidth(s[0])+7,y-2,W-right-20,y-2); doc.setLineDashPattern([],0); y+=20; }); footer();

sections.forEach((s,idx)=>{ doc.addPage(); y=top; heading(s[0]); s[1].forEach(b=>bullet(b)); if(idx===1){ y+=8; ensure(82); doc.setFillColor(255,247,230); doc.setDrawColor(235,170,45); doc.roundedRect(left,y,W-left-right,70,5,5,"FD"); doc.setFont("helvetica","bold"); doc.setFontSize(10); doc.setTextColor(145,90,15); doc.text("DUPLICATE-CHARGE WARNING",left+14,y+20); doc.setFont("helvetica","normal"); const t=doc.splitTextToSize("Never run the customer's card again until the first attempt has been checked and confirmed as failed or canceled.",W-left-right-28); doc.text(t,left+14,y+40); y+=80; } footer(); });

// Final quick-reference page
 doc.addPage(); y=top; heading("Quick Troubleshooting Decision Guide"); const quick=[
 ["Kiosk shows confirmation","Prepare the order."],
 ["Terminal approved; kiosk still waiting","Check Admin Panel and Square. Do not charge again."],
 ["Terminal declined","Retry once or use another card."],
 ["Payment canceled","Confirm cancellation, then retry."],
 ["Reader timed out","Verify the first attempt before retrying."],
 ["Reader not connected","Check power, network, and pairing."],
 ["Card form unavailable","Use the paired Terminal or notify a manager."],
 ["Paid order missing from kitchen","Do not recharge; locate the order and notify a manager."]
 ]; quick.forEach(([a,b])=>{ ensure(54); doc.setFillColor(245,248,250); doc.roundedRect(left,y,W-left-right,44,4,4,"F"); doc.setFont("helvetica","bold"); doc.setFontSize(10); doc.setTextColor(...blue); doc.text(a,left+12,y+17); doc.setFont("helvetica","normal"); doc.setTextColor(...dark); doc.text(doc.splitTextToSize(b,W-left-right-24),left+12,y+33); y+=52; }); footer();

const out = path.resolve("Jiggling_Pig_Kiosk_Square_Terminal_User_Guide.pdf");
fs.writeFileSync(out, Buffer.from(doc.output("arraybuffer")));
console.log(out, fs.statSync(out).size, doc.getNumberOfPages());
