// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pickup-redesign/Current.tsx": () => import("../components/mockups/pickup-redesign/Current.tsx"),
  "./components/mockups/pickup-redesign/Working.tsx": () => import("../components/mockups/pickup-redesign/Working.tsx")
};
